// LOCALHOST

### Get all contacts
GET http://localhost:8085/contacts


### Get contact by id
GET http://localhost:8085/contacts/65d6253d54cec76b2a133228


### POST - Create contact
POST http://localhost:8085/contacts 
content-type: application/json

{
    "firstName":"Amanda",
    "lastName":"Webber",
    "email":"awww@test.com",
    "phone":"204-918-4886",
    "address":"124 Academy Rd, Wpg, Canada R4T 4S4"
}


### PUT or Update contact
PUT http://localhost:8085/contacts/65d625b754cec76b2a13322b 
content-type: application/json

{
    "firstName":"Andres",
    "lastName":"Brown",
    "email":"andreabrown@test.com",
    "phone":"405-903-1515",
    "address":"66 Main St, Edmonton, Canada R4T 4S4"
}


### DELETE contact
DELETE http://localhost:8085/contacts/65debc87989c996667b6d355

