// LOCALHOST
### Get all contacts
GET http://localhost:8080/contacts


### Get contact by id
GET http://localhost:8080/contacts/622023f642f9ab4cd6e060b3


### Create contact
POST http://localhost:8080/contacts 
content-type: application/json

{
    "firstName":"Antony",
    "lastName":"Webber",
    "email":"aaawww@test.com",
    "phone":"204-918-4556",
    "address":"124 Academy Rd, Wpg, Canada R4T 4S4"
}


### PUT contact
PUT http://localhost:8080/contacts/6220bcb39cd507e920c75a0b HTTP/1.1
content-type: application/json

{
    "firstName":"Andres",
    "lastName":"Brown",
    "email":"andreab@test.com",
    "phone":"405-903-1515",
    "address":"66 Main St, Edmnton, Canada R4T 4S4"
}


### DELETE contact
DELETE http://localhost:8080/contacts/6220b775099269ff7b31ceab HTTP/1.1



//Ask the teacher about herokuapp.

// PRODUCTION Deploy
### Get all contacts
GET https://cse341-instructor.herokuapp.com/contacts


### Get contact by id
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b3


### Create contact
POST https://cse341-instructor.herokuapp.com/contacts HTTP/1.1
content-type: application/json

{
     "firstName":"Antony",
    "lastName":"Webber",
    "email":"aaawww@test.com",
    "phone":"204-918-4556",
    "address":"124 Academy Rd, Edmnton, Canada R4T 4S4"
}


### PUT contact
PUT https://cse341-instructor.herokuapp.com/contacts/6220bcb39cd507e920c75a0b HTTP/1.1
content-type: application/json

{
     "firstName":"Andres",
    "lastName":"Brown",
    "email":"andreab@test.com",
    "phone":"405-903-1515",
    "address":"66 Main St, Edmnton, Canada R4T 4S4"
}


### DELETE contact
DELETE https://cse341-instructor.herokuapp.com/contacts/6220e34083149913680f9a64 HTTP/1.1